added a away to get the signings from N days ago
Dillonb/CSCrew2015-back pull request #1
Opened 2016-09-30 00:13 UTC by jaywunder

2016-09-30 17:41 UTC, Dillonb requested changes
Good direction but has a few issues.

2016-09-30 17:41 UTC, Dillonb commented on functions.php
> +   $processedMembers = array();
grrr whitespace changes in a PR

2016-09-30 17:41 UTC, Dillonb commented on functions.php
> +    $oneDayInMS = 24 * 60 * 60 * 100
This should be 24 * 60 * 60 * 1000, or just 86400 * 1000.


Also you forgot a semicolon :)

2016-09-30 17:41 UTC, Dillonb commented on functions.php
> +    $signins = signInQuery::create()->filterByCreatedAt(array('min'=>$dayBeginning), 'max'=>$dayEnd)->find();
Consider looking into other ways to do this query - I know SQL can take dates as strings instead of timestamps.

2016-09-30 17:41 UTC, Dillonb commented on functions.php
> +    $dayEnd = $beginOfDay - ($oneDayInMS * ($daysAgo - 1))
Semicolons on the two lines above

2016-09-30 19:56 UTC, Dillonb commented
I can also test this for you / help you get set up to test it.

2016-10-04 15:51 UTC, junewunder commented on functions.php
> +   $processedMembers = array();
lol that was atom, not me I think

2016-10-04 15:53 UTC, jaywunder commented on functions.php
> +    $signins = signInQuery::create()->filterByCreatedAt(array('min'=>$dayBeginning), 'max'=>$dayEnd)->find();
Why not use timestamps?  I think this way is easier

2016-10-12 00:55 UTC, jaywunder commented
@Dillonb

2016-10-12 18:14 UTC, closed without merging

2016-10-12 18:18 UTC, Dillonb commented
Merged manually. Closing this.